### ISSUE TITLE
Error with installing requirements

### ISSUE THREAD

**Issue by boodi4321** [CHEGEBB/IMEI-TRACKER#11]
C:\Users\HP\IMEI-TRACKER>pip install -r **requirements**.txt
Collecting requests==2.26.0 (from -r requirements.txt (line 1))
  Using cached requests-2.26.0-py2.py3-none-any.whl.metadata (4.8 kB)
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

**Comment by CHEGEBB** [comment]
do this first python -m pip install --upgrade pip then run the command to install the requiremennts assume this
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter
the script will run
