### ISSUE TITLE
Python ModuleNotFound Error

### ISSUE THREAD

**Issue by Pingu6855** [CHEGEBB/IMEI-TRACKER#3]
Hey there,
so I'm new to python so i dont really know my way arround it. But for what i can see is that it can't find the requests module... Ive tried reinstalling Python (3.12) but it keeps throwing me the same error. Any ideas on how I can fix this?
Cheers
![image](https://github.com/CHEGEBB/IMEI-TRACKER/assets/146462582/fe35f732-f313-488d-aa86-b3a0c68dcc3f)

**Comment by CHEGEBB** [comment]
Hello 👋. Can you try installing requests as a module on its own and try
running the script again to see if it works?

**Comment by CHEGEBB** [comment]
pip install requests

**Comment by Pingu6855** [comment]
Ends up giving me the same issue...
![image](https://github.com/CHEGEBB/IMEI-TRACKER/assets/146462582/3d3cca78-0a14-438c-a668-5d818b024f10)

**Comment by CHEGEBB** [comment]
can you check you python version
python --version

**Comment by Pingu6855** [comment]
It says here I'm running 3.10.9

**Comment by CHEGEBB** [comment]
get the latest and try again below's the link
https://www.python.org/downloads/

**Comment by Pingu6855** [comment]
same issue
I'll try a different Pc
